name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure the full history is fetched
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          echo "Building the project..."

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Directory containing the files to publish
          publish_branch: gh-pages  # Branch in the public repo to deploy to
          external_repository: praveenreddy54/pse  # Public repo name
